### ISSUE TITLE
Redirect users to original page they tried to access after login

### ISSUE THREAD

**Issue by shakamal** [witrin/magento-authorization#1]
I'd like to be able to redirect users to the original (restricted) CMS page they attempted to access after they login or register.

**Comment by witrin** [comment]
For that you have to set the Magento backend setting `Redirect Customer to Account Dashboard after Logging in` to `No` under `System > Configuration > Customer Configuration > Login Options`. Please excuse my late answer, I was not sure if I'd already implemented this.
