### ISSUE TITLE
How to separate Public Actions?

### ISSUE THREAD

**Issue by Commercers** [witrin/magento-authorization#3]
Hi,
I am trying to get more than one action to be public. Right now the login page is public by using
`/customer\/account\/login.*/`
in the form.
Furtheron I want the contacts and the forgot password page to be public. How do I get this done?

I already tried
`/customer\/account\/login.*/,/contacts/`
`/customer\/account\/login.*/;/contacts/`
...

But no success so far.
Furtheron: I am wondering why you have to define the login page to be public seperately. Shouldn't it be public by default?

Thanks for help!

Best regards, Covos

**Comment by witrin** [comment]
Hi Covos,

checkout the documentation, you'll find some examples how to make the 'Forgot Password' action public. To make also some actions of the `Mage_Contacts` module public, like `index` and `post`, maybe this is the right expression for you:

`/(customer\/account\/(index|login|forgotpassword|resetpassword|logoutSuccess)|contacts\/index\/(index|post))/`

Please note, the field `Public Actions` is for only one regular expression not a list of them, like you tried. I explained this also in the documentation!

Login is not public by default, because there are multiple actions like `resetpassword` and `create` that not everyone wants to publish, thus I give you the ability to customize it to your needs.

Kind regards,
Artus

**Comment by Commercers** [comment]
Hi Artus,

thanks! This seems to work.

Best regards,

Leonhard

---

Logoschwarz-auf-weiss-100px 

Kreative und funktionale eCommerce Lösungen nach Maß:
Onlineshops (B2C), Werbemittelabrufsysteme (B2B) & mehr

.commercers Blog rund um Magento http://www.commercers.com/blog 

 mailto:vonschwerin@commercers.com vonschwerin@commercers.com
 blocked::http://www.commercers.com/ http://www.commercers.com

Commercers GmbH – Parchimer Str. 1 - 19386 Lübz
fon: +49-38731-39982-1 - fax: +49-38731-3998-19
USt.-ID. DE 281358024 Handelsregister: HRB 11123 - Amtsgericht Schwerin
Geschäftsführer: Oliver Hinsenbrock, Leonhard Graf von Schwerin

Diese E-Mail enthält vertrauliche und/oder rechtlich geschützte Informationen. Wenn Sie nicht der richtige Adressat sind oder diese E-Mail irrtümlich erhalten haben, informieren Sie bitte sofort den Absender und vernichten Sie diese Mail. Das unerlaubte Kopieren sowie die unbefugte Weitergabe dieser Mail ist nicht gestattet.

This e-mail may contain confidential and/or privileged information. If you are not the intended recipient (or have received this e-mail in error) please notify the sender immediately and destroy this e-mail. Any unauthorized copying, disclosure or distribution of the material in this e-mail is strictly forbidden. 

Von: Artus Kolanowski [mailto:notifications@github.com] 
Gesendet: Dienstag, 23. Juli 2013 14:27
An: witrin/magento-authorization
Cc: .commercers
Betreff: Re: [magento-authorization] How to separate Public URLs? (#3)

Hi Covos,

checkout the documentation. You'll find some examples how to make the 'Forgot Password' action public. To make also some actions of the Mage_Contacts module public, like index and post, maybe this is the right expression for for you:

/(customer\/account\/(index|login|forgotpassword|resetpassword|logoutSuccess)|contacts\/index\/(index|post))/

Please note, the field Public Actions is for only one regular expression not a list of them, like you tried. I explained this also in the documentation!

Login is not public by default, because there are multiple actions like resetPassword and create that not everyone wants to publish, thus I give you the ability to customize it to your needs.

Kind regards,
Artus

**Comment by witrin** [comment]
I'm glad to hear it. About a review on www.magentocommerce.com I'd be happy.
