### ISSUE TITLE
Undefined property: Ionoi_Authorization_Helper_Store::$_getPageIdentifier

### ISSUE THREAD

**Issue by loiacono** [witrin/magento-authorization#4]
Hi, and thanks for your extension.
I've been working both on Magento 1.8 and lately on 1.8.1, both on live server and on local MAMP.
In system.log I get many `ERR (3)` registrations with the following message:
`Undefined property: Ionoi_Authorization_Helper_Store::$_getPageIdentifier  in <my_path>/app/code/community/Ionoi/Authorization/Helper/Store.php on line 102`.

Actually on line 102 I find:
`$result = array_map($this->_getPageIdentifier, explode(',', $config));`

where it looks like  `_getPageIdentifier` misses its argument and parentheses.

Can you help

**Comment by witrin** [comment]
Ups, that's a bug. Replace line 102 with this:

`$result = array_map(array($this, '_getPageIdentifier'), explode(',', $config));`

**Comment by loiacono** [comment]
Thanks, witrin. I try it right now.

**Comment by loiacono** [comment]
No more errors.
Thanks.
