### ISSUE TITLE
General setup question?

### ISSUE THREAD

**Issue by Brian24** [witrin/magento-authorization#5]
Hello Witrin,

Thank you very much for offering Store Permissions for free!  The plugin looks really good, but I am just having some trouble figuring out how to setup the permissions.

What I would like to do is to block access to my site for anyone that visits it, with the exception of one group.  I setup a group call “Preview”.  I would like to grant this group full access to my site. 

Currently, when when I type in my website’s url, I get a redirect error, which is fine.  Now, I just need to know how to grant access to one group “Preview”. 

Can you please explain how to do this?  

Thanks!

**Comment by witrin** [comment]
Would you like to upload a screenshot with your current configuration (in English would be best)?

**Comment by Brian24** [comment]
OK, screenshot is attached.

I just added a line in the Public Actions.  This brings up the login screen, but once I login, I cannot see any items on my website.  

Thanks!

![2014-shot](https://f.cloud.github.com/assets/6454732/1958770/af5823c6-821f-11e3-817a-f0d8e1fd610e.jpg)

**Comment by witrin** [comment]
I've tested your configuration without any problems in a demo environment. What do you mean with "I cannot see any items on my website" can you be more specific? Do you have any entries in your `error.log`?

**Comment by Brian24** [comment]
Everything works now.  I had to reindex my Product Prices and once I did that, all items appeared.  

Thanks again and I appreciate the help.

**Comment by witrin** [comment]
You're welcome!
